import { test, expect } from '@playwright/test'
import { completeQuick, finishReflection, openApp, openArrival } from './helpers'

test.describe('First run and shell', () => {
  test('completes onboarding without selecting a theory', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByRole('dialog')).toContainText(/exploration, not a test/i)
    await page.getByRole('button', { name: 'Next' }).click()
    await expect(page.getByRole('dialog')).toContainText(/your context matters/i)
    await page.getByRole('button', { name: 'Next' }).click()
    await expect(page.getByRole('heading', { name: 'Privacy & data' })).toBeVisible()
    await expect(page.getByRole('switch', { name: 'Save reflections on this device' })).toBeChecked()
    await expect(page.getByText(/stored only on this device/i)).toBeVisible()
    await expect(page.getByRole('dialog')).not.toContainText(/Plutchik|Emotion Wheel/)
    await page.getByRole('button', { name: 'Get started' }).click()
    await expect(page.getByTestId('today-screen')).toBeVisible()
  })

  test('restores exact destinations with browser Back and Forward', async ({ page }) => {
    await openApp(page)
    await page.getByRole('button', { name: 'Start a reflection' }).click()
    await expect(page.getByTestId('arrival-screen')).toBeVisible()
    await page.goBack()
    await expect(page.getByTestId('today-screen')).toBeVisible()

    await page.goForward()
    await expect(page.getByTestId('arrival-screen')).toBeVisible()

    await page.getByRole('button', { name: 'Explore' }).click()
    await expect(page.getByTestId('explore-screen')).toBeVisible()
    await page.goBack()
    await expect(page.getByTestId('explore-screen')).toBeVisible()
    await page.goForward()
    await expect(page.getByTestId('explore-screen')).toBeVisible()

    await page.getByRole('button', { name: 'Settings' }).click()
    await page.getByRole('button', { name: 'Privacy & data' }).click()
    await expect(page.getByTestId('privacy-screen')).toBeVisible()
    await page.goBack()
    await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
    await page.goForward()
    await expect(page.getByTestId('privacy-screen')).toBeVisible()

    await page.goBack()
    await page.goBack()
    await expect(page.getByTestId('explore-screen')).toBeVisible()
    await page.getByRole('button', { name: 'Journal', exact: true }).click()
    await expect(page.getByTestId('journal-screen')).toBeVisible()
  })

  test('switches language and shows offline state', async ({ page, context }) => {
    await openApp(page)
    await page.getByRole('button', { name: 'Settings' }).click()
    const languageGroup = page.getByRole('group', { name: 'Language' })
    const english = languageGroup.getByRole('button', { name: 'EN' })
    const romanian = languageGroup.getByRole('button', { name: 'RO' })
    await expect(english).toHaveAttribute('aria-pressed', 'true')
    await expect(romanian).toHaveAttribute('aria-pressed', 'false')
    await romanian.click()
    await expect(page.getByRole('group', { name: 'Limbă' }).getByRole('button', { name: 'RO' })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('heading', { name: 'Setări' })).toBeVisible()
    await page.getByRole('button', { name: 'Înapoi' }).click()
    await expect(page.getByRole('button', { name: 'Astăzi' })).toBeVisible()

    await context.setOffline(true)
    await expect(page.getByRole('status')).toContainText(/offline/i)
    await context.setOffline(false)
  })
})

test.describe('Primary check-in routes', () => {
  test.beforeEach(async ({ page }) => openApp(page))

  test('Quick requires one explicit commitment after selection', async ({ page }) => {
    const anxiety = page.getByTestId('quick-feeling-anxiety')
    await anxiety.click()

    await expect(page.getByTestId('today-screen')).toBeVisible()
    await expect(page.getByTestId('reflection-screen')).toHaveCount(0)
    await expect(anxiety).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('button', { name: 'Continue with anxiety' })).toBeInViewport()

    await page.getByTestId('quick-feeling-joy').click()
    await expect(anxiety).toHaveAttribute('aria-pressed', 'false')
    await expect(page.getByRole('button', { name: 'Continue with joy' })).toBeVisible()
    await page.getByTestId('quick-continue').click()
    await expect(page.getByTestId('reflection-screen')).toBeVisible()
  })

  test('quick feeling reaches Meaning + Need and saves to Journal', async ({ page }) => {
    await completeQuick(page, 'anxiety')
    await expect(page.getByRole('heading', { name: 'What seems to fit?' })).toBeVisible()
    await expect(page.getByText(/may be close. Keep only what fits your experience/i)).toBeVisible()
    await expect(page.locator('.more-context')).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'grounding', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Yes' }).click()
    await page.getByRole('button', { name: 'Explore further' }).click()
    const moreContext = page.locator('.more-context')
    await moreContext.getByText('More context').click()
    await expect(moreContext).toContainText(/closest match among these suggestions/i)
    await expect(moreContext).not.toContainText(/you are experiencing|your system is responding/i)
    const need = page.getByRole('button', { name: 'grounding', exact: true })
    await expect(need).toHaveAttribute('aria-pressed', 'false')
    await need.click()
    await finishReflection(page)

    await page.getByRole('button', { name: 'Journal', exact: true }).click()
    await expect(page.getByTestId('journal-screen')).toContainText(/anxiety/i)
    await page.getByRole('button', { name: /open reflection: anxiety/i }).click()
    await expect(page.getByTestId('session-detail-screen')).toContainText(/yes/i)
    await expect(page.getByTestId('session-detail-screen')).toContainText('grounding')
  })

  test('does not persist when local saving is disabled', async ({ page }) => {
    await page.getByRole('button', { name: 'Settings' }).click()
    await page.getByRole('button', { name: 'Privacy & data' }).click()
    await page.getByRole('switch', { name: 'Save reflections on this device' }).click()
    await page.getByRole('button', { name: 'Back' }).click()
    await page.getByRole('button', { name: 'Back' }).click()
    await completeQuick(page, 'joy')
    await finishReflection(page)
    await page.getByRole('button', { name: 'Journal', exact: true }).click()
    await expect(page.getByText('No saved reflections yet')).toBeVisible()
  })

  test('Body Compass collects region, sensation, intensity and reflects', async ({ page }) => {
    await openArrival(page)
    await page.getByTestId('arrival-body').click()
    await expect(page.getByTestId('body-screen')).toBeVisible()
    expect(await page.locator('.app-content').evaluate((element) => element.scrollTop)).toBe(0)
    await page.getByRole('button', { name: 'Front', exact: true }).click()

    await page.locator('[data-region="chest"]').first().click({ force: true })
    await expect(page.getByRole('heading', { name: 'What do you feel here?' })).toBeVisible()
    await page.getByRole('button', { name: 'Tension' }).click()
    await page.getByRole('button', { name: /moderate/i }).click()
    await expect(page.getByRole('heading', { name: 'Where do you notice a body sensation?' })).toBeVisible()
    await expect(page.getByTestId('body-signal-chest')).toBeFocused()
    await page.getByRole('button', { name: 'See what might fit' }).click()
    await expect(page.getByTestId('reflection-screen')).toBeVisible()
  })

  test('Affect Map reveals suggestions after placement', async ({ page }) => {
    await openArrival(page)
    await page.getByTestId('arrival-affect').click()
    const plot = page.getByTestId('dimensional-plot-container').locator('svg')
    await expect(plot).toBeVisible()
    await expect(page.getByTestId('affect-placement-hint')).toBeVisible()
    const axisLabel = page.getByText('Unpleasant', { exact: true })
    expect((await axisLabel.boundingBox())!.height).toBeGreaterThanOrEqual(11)
    const box = await plot.boundingBox()
    expect(box).not.toBeNull()
    await plot.click({ position: { x: box!.width * 0.7, y: box!.height * 0.25 }, force: true })
    await expect(page.getByTestId('affect-placement-hint')).toHaveCount(0)
    await expect(page.getByTestId('affect-readout')).toBeVisible()
    const tray = page.getByTestId('dimensional-suggestion-tray')
    const firstSuggestion = tray.locator('.dimensional-suggestion-chip').first()
    await expect(firstSuggestion).toBeInViewport()
    await firstSuggestion.click()
    await expect(firstSuggestion).toHaveAttribute('aria-pressed', 'true')
    await expect(tray).toBeVisible()
    await page.getByRole('button', { name: 'Reflect on these words' }).click()
    await expect(page.getByTestId('reflection-screen')).toBeVisible()
  })

  test('Word Ladder moves broad to precise and reflects', async ({ page }) => {
    await openArrival(page)
    await page.getByTestId('arrival-words').click()
    const options = page.getByRole('list', { name: 'Choose one direction' })
    await options.getByRole('button').first().click()
    await options.getByRole('button').first().click()
    await options.getByRole('button').first().click()
    await expect(page.locator('.route-action button')).toBeEnabled()
    await page.locator('.route-action button').click()
    await expect(page.getByTestId('reflection-screen')).toBeVisible()
  })

  test('Plutchik combines two primary emotions in a stable wheel', async ({ page }) => {
    await page.getByRole('button', { name: 'Explore' }).click()
    await page.getByTestId('explore-plutchik').click()
    const wheel = page.getByRole('group', { name: 'Eight starting emotions from the Plutchik model, arranged as a wheel' })
    await expect(wheel).toBeVisible()
    await expect(page.getByTestId(/^plutchik-emotion-/)).toHaveCount(8)
    await page.getByTestId('plutchik-emotion-joy').click()
    await page.getByTestId('plutchik-emotion-trust').click()
    await expect(page.getByTestId('plutchik-combination')).toContainText(/joy \+ trust.*love/i)
    await expect(page.getByTestId('plutchik-emotion-anger')).toBeDisabled()
    await expect(page.locator('.route-action button')).toBeEnabled()
  })
})

test.describe('Safety behavior through the UI', () => {
  test('tier 4 support is first and gates reflection details', async ({ page }) => {
    await openApp(page)
    await page.evaluate(() => localStorage.setItem('emot-id-allow-external-ai', 'true'))
    await page.reload()
    await openArrival(page)
    await page.getByTestId('arrival-words').click()

    const choose = async (name: RegExp) => page.getByRole('list', { name: 'Choose one direction' }).getByRole('button', { name }).click()

    await choose(/^sad/i)
    await choose(/^despair/i)
    await page.getByRole('button', { name: 'Add Despair' }).click()

    await choose(/^sad/i)
    await choose(/^depressed/i)
    await choose(/^empty/i)

    await choose(/^fearful/i)
    await choose(/^weak/i)
    await choose(/^worthless/i)

    await page.locator('.route-action button').click()
    await expect(page.getByRole('button', { name: 'Settings' })).toHaveCount(0)
    const alert = page.getByRole('alert')
    const support = page.locator('.crisis-banner')
    await expect(alert).toBeVisible()
    await expect(page.locator('.emotion-heading')).not.toBeVisible()
    await expect(page.getByRole('group', { name: 'What might help most right now?' })).toHaveCount(0)
    await expect(page.getByRole('link', { name: 'Explore in Google AI Mode' })).toHaveCount(0)
    await expect(alert).toContainText(/do not tell Emot-ID whether you are in danger/i)
    await expect(support.getByRole('link', { name: /deprehub/i })).toHaveAttribute('href', 'tel:+40374456420')
    await expect(page.getByRole('button', { name: 'Continue to reflection' })).toBeVisible()

    const alertBox = await support.boundingBox()
    const ackBox = await page.getByRole('button', { name: 'Continue to reflection' }).boundingBox()
    expect(alertBox!.y).toBeLessThan(ackBox!.y)

    await page.getByRole('button', { name: 'Continue to reflection' }).click()
    await expect(page.locator('.emotion-heading')).toContainText(/despair/i)
    await expect(page.locator('.meaning-block')).toHaveCount(0)
    await expect(page.getByRole('group', { name: 'What might help most right now?' })).toHaveCount(0)
    await expect(page.getByRole('link', { name: 'Explore in Google AI Mode' })).toHaveCount(0)
    await page.getByRole('button', { name: 'Explore further' }).click()
    await expect(page.locator('.meaning-block')).toContainText(/future seeming closed/i)
    await expect(page.locator('.meaning-block')).toContainText(/lost hope rather than low mood alone/i)
    await expect(page.getByRole('group', { name: 'What might help most right now?' })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Explore in Google AI Mode' })).toBeVisible()
  })
})

test.describe('Privacy and support destinations', () => {
  test('allows the existing Google AI Mode link by default and persists opt-out', async ({ page }) => {
    await openApp(page)
    await completeQuick(page, 'anxiety')
    await expect(page.getByRole('link', { name: 'Explore in Google AI Mode' })).toHaveCount(0)
    await page.getByRole('button', { name: 'Explore further' }).click()
    const link = page.getByRole('link', { name: 'Explore in Google AI Mode' })
    await expect(link).toBeVisible()
    await expect(link).toHaveAttribute('target', '_blank')
    const href = await link.getAttribute('href')
    const url = new URL(href!)
    expect(url.origin + url.pathname).toBe('https://www.google.com/search')
    expect(url.searchParams.get('udm')).toBe('50')
    expect(url.searchParams.get('q')).toBe(
      'I feel anxiety. What does this emotion mean and how can I understand it better?',
    )
    await expect(page.getByText(/opens Google AI Mode with a fixed question/i)).toBeVisible()
    await expect(page.getByText(/not a substitute for professional support/i)).toBeVisible()

    await page.getByRole('button', { name: 'Back' }).click()
    await expect(page.getByTestId('reflection-screen')).toBeVisible()
    await page.getByRole('button', { name: 'Back' }).click()
    await expect(page.getByTestId('today-screen')).toBeVisible()
    await page.getByRole('button', { name: 'Settings' }).click()
    await page.getByRole('button', { name: 'Privacy & data' }).click()
    const aiSwitch = page.getByRole('switch', { name: 'Allow Google AI Mode links' })
    await expect(aiSwitch).toBeChecked()
    await aiSwitch.click()
    await expect(aiSwitch).not.toBeChecked()

    await page.reload()
    await completeQuick(page, 'joy')
    await page.getByRole('button', { name: 'Explore further' }).click()
    await expect(page.getByRole('link', { name: 'Explore in Google AI Mode' })).toHaveCount(0)
    await expect(page.getByText(/Google AI Mode links are off/i)).toBeVisible()
  })

  test('settings separates privacy and support from product navigation', async ({ page }) => {
    await openApp(page)
    await page.getByRole('button', { name: 'Settings' }).click()
    await expect(page.getByText('Simple language')).toHaveCount(0)
    await expect(page.getByText('Sound effects')).toHaveCount(0)
    await expect(page.getByText('Daily reminder')).toHaveCount(0)
    const appearance = page.getByRole('group', { name: 'Appearance' })
    await expect(appearance.getByRole('button', { name: 'Light' })).toHaveAttribute('aria-pressed', 'true')
    await appearance.getByRole('button', { name: 'Dark' }).click()
    await expect(appearance.getByRole('button', { name: 'Dark' })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    await page.getByRole('button', { name: 'Privacy & data' }).click()
    await expect(page.getByTestId('privacy-screen')).toContainText(/no account, analytics, or cloud sync/i)
    await page.getByRole('button', { name: 'Back' }).click()
    await page.getByRole('button', { name: 'Support' }).click()
    await expect(page.getByTestId('support-screen')).toContainText('0374 456 420')
  })
})
